# Generated by Django 5.2.4 on 2025-07-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antrian',
            name='nik',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antrian',
            name='rt',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antrian',
            name='rw',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antriansession',
            name='kegiatan',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
