# Generated by Django 5.2.4 on 2025-07-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0002_antrian_nik_antrian_rt_antrian_rw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antrian',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='antrian',
            name='rt',
            field=models.CharField(blank=True, choices=[('1', '01'), ('2', '02'), ('3', '03'), ('4', '04'), ('5', '05'), ('6', '06'), ('7', '07'), ('8', '08'), ('9', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='antrian',
            name='rw',
            field=models.CharField(blank=True, choices=[('1', '01'), ('2', '02'), ('3', '03'), ('4', '04'), ('5', '05'), ('6', '06'), ('7', '07'), ('8', '08'), ('9', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=2, null=True),
        ),
    ]
