# Generated by Django 5.2.4 on 2025-07-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0003_alter_antrian_nik_alter_antrian_rt_alter_antrian_rw'),
    ]

    operations = [
        migrations.AddField(
            model_name='antrian',
            name='Keterangan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
