# Generated by Django 5.2.5 on 2025-10-22 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kependudukan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('tanah', 'Tanah'), ('bangunan', 'Bangunan'), ('kendaraan', 'Kendaraan'), ('ternak', 'Ternak'), ('pertanian', 'Pertanian'), ('usaha', 'Usaha'), ('lainnya', 'Lainnya')], max_length=20)),
                ('sub_kategori', models.CharField(blank=True, max_length=100, null=True)),
                ('nama', models.CharField(max_length=255)),
                ('no_ktp', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
                ('rt_rw', models.CharField(blank=True, max_length=20, null=True)),
                ('desa', models.CharField(blank=True, max_length=100, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=100, null=True)),
                ('lokasi_lahan', models.CharField(blank=True, max_length=255, null=True)),
                ('no_sppt', models.CharField(blank=True, max_length=100, null=True)),
                ('no_c_petok', models.CharField(blank=True, max_length=100, null=True)),
                ('persil', models.CharField(blank=True, max_length=100, null=True)),
                ('kelas', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_c', models.CharField(blank=True, max_length=100, null=True)),
                ('luasc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('luas_mohon', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('luas_sppt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nib', models.CharField(blank=True, max_length=50, null=True)),
                ('utara', models.CharField(blank=True, max_length=255, null=True)),
                ('timur', models.CharField(blank=True, max_length=255, null=True)),
                ('selatan', models.CharField(blank=True, max_length=255, null=True)),
                ('barat', models.CharField(blank=True, max_length=255, null=True)),
                ('jumlah', models.PositiveIntegerField(blank=True, null=True)),
                ('nilai_taksiran', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('pemilik_luar', models.BooleanField(default=False)),
                ('tahun_data', models.PositiveIntegerField(default=2025)),
                ('penduduk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kependudukan.penduduk')),
            ],
            options={
                'verbose_name': 'Aset',
                'verbose_name_plural': 'Daftar Aset',
                'ordering': ['-tahun_data', 'nama'],
            },
        ),
    ]
