# Generated by Django 5.2.5 on 2025-11-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aset',
            name='no_ktp',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
