# Generated by Django 5.2.5 on 2025-10-22 10:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostingInvestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('isi', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='berita_gambar/')),
                ('tanggal_terbit', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
