# Generated by Django 5.2.5 on 2025-10-22 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KartuKeluarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kk', models.CharField(max_length=20, unique=True, verbose_name='Nomor KK')),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_rt', models.CharField(blank=True, max_length=5, null=True, verbose_name='RT')),
                ('no_rw', models.CharField(blank=True, max_length=5, null=True, verbose_name='RW')),
                ('kode_pos', models.CharField(blank=True, max_length=10, null=True, verbose_name='Kode Pos')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='kependudukan.kartukeluarga', verbose_name='KK Induk / Asal')),
            ],
        ),
        migrations.CreateModel(
            name='Penduduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=20, unique=True, verbose_name='NIK')),
                ('nama_lgkp', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('jenis_klmin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('jenis_klmin_ket', models.CharField(blank=True, max_length=20, null=True, verbose_name='Keterangan Jenis Kelamin')),
                ('tmpt_lhr', models.CharField(max_length=50, verbose_name='Tempat Lahir')),
                ('tgl_lhr', models.DateField(verbose_name='Tanggal Lahir')),
                ('agama', models.CharField(blank=True, max_length=10, null=True, verbose_name='Agama (kode)')),
                ('agama_ket', models.CharField(max_length=50, verbose_name='Agama')),
                ('pddk_akh', models.CharField(blank=True, max_length=10, null=True, verbose_name='Kode Pendidikan')),
                ('pendidikan_akh_ket', models.CharField(max_length=50, verbose_name='Pendidikan Terakhir')),
                ('jenis_pkrjn', models.CharField(blank=True, max_length=10, null=True, verbose_name='Kode Pekerjaan')),
                ('jenis_pkrjn_ket', models.CharField(max_length=50, verbose_name='Pekerjaan')),
                ('gol_drh', models.CharField(blank=True, max_length=5, null=True, verbose_name='Golongan Darah')),
                ('stat_kwn_ket', models.CharField(max_length=30, verbose_name='Status Kawin')),
                ('tgl_kwn', models.DateField(blank=True, null=True, verbose_name='Tanggal Kawin')),
                ('stat_hbkel', models.CharField(blank=True, max_length=10, null=True, verbose_name='Status Hubungan Keluarga (kode)')),
                ('stat_hbkel_1', models.CharField(max_length=30, verbose_name='Hubungan Keluarga')),
                ('alamat', models.TextField()),
                ('no_rt', models.CharField(max_length=5, verbose_name='RT')),
                ('no_rw', models.CharField(max_length=5, verbose_name='RW')),
                ('dusun', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dusun')),
                ('kode_pos', models.CharField(blank=True, max_length=10, null=True, verbose_name='Kode Pos')),
                ('telp', models.CharField(blank=True, max_length=20, null=True, verbose_name='No Telepon')),
                ('no_prop', models.CharField(max_length=5, verbose_name='Kode Provinsi')),
                ('nama_prop', models.CharField(max_length=50, verbose_name='Nama Provinsi')),
                ('no_kab', models.CharField(max_length=5, verbose_name='Kode Kabupaten')),
                ('nama_kab', models.CharField(max_length=50, verbose_name='Nama Kabupaten')),
                ('no_kec', models.CharField(max_length=5, verbose_name='Kode Kecamatan')),
                ('nama_kec', models.CharField(max_length=50, verbose_name='Nama Kecamatan')),
                ('no_kel', models.CharField(max_length=5, verbose_name='Kode Kelurahan')),
                ('nama_kel', models.CharField(max_length=50, verbose_name='Nama Kelurahan')),
                ('no_kk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penduduk_set', to='kependudukan.kartukeluarga')),
            ],
        ),
    ]
