# Generated by Django 5.2.5 on 2025-11-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kependudukan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penduduk',
            name='status_hidup',
            field=models.BooleanField(default=True, verbose_name='Hidup'),
        ),
    ]
