# Generated by Django 5.2.5 on 2025-11-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kependudukan', '0002_penduduk_status_hidup'),
    ]

    operations = [
        migrations.AddField(
            model_name='penduduk',
            name='tgl_meninggal',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Meninggal'),
        ),
    ]
